### ISSUE TITLE
on a makerbot with an MK5 the extruder heater stops midprint

### ISSUE THREAD

**Issue by chgray** [makerbot/ReplicatorG#111]
midprint the relay snaps on the MK5 and the temperature starts to drop. the relay does not turn back on and eventually the temp drops so low the plastic cannot ooze and everything wedges up. note that the print is continuing, the x/y/z motors are working

from the Control Panel in ReplicatorG I can turn on the heater and the problem reproduces

I think the problem is software for the following reasons
1. my extruder controller is also driving a heated platform without problem - that leads me to believe the ethernet cable between the main board and the extruder board is okay
2. if after it wedges I go into the 'Homing' ctrl panel I can turn up the heat, without reseting anything
3. the motor pushing the plastic is still going, this broke my MK4 and my MK5 is much stronger
4. I've verified the problem on a mac, PC, and with an SD card

more info can be found here http://wiki.makerbot.com/forum/t-266818/mid-print-mk5-heater-just-stops-print-continues

**Comment by D1plo1d** [comment]
Same problem here. I have a MK4 although I think my extruder motor stops as well but it could just be completely stalled because the filament has solidified in the extruder.

This is happening on _every_ print now. Please help!

I am using the replicatorG master head with some modification for my queue stuff but that should be unrelated code.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
