### ISSUE TITLE
Correlate driver with machine name

### ISSUE THREAD

**Issue by koenkooi** [makerbot/ReplicatorG#121]
I have a cupcake and a mendel and I'm using repG for both, but I sometimes forget to switch the driver to the machine.xml entry I created for my mendel. It would be nice if repG would remember the driver by matching the firmware machine name.

Alternatively the firmware could store things like axis length and motor scaling.

**Comment by phooky** [comment]
The cupcake and mendel use different protocols to identify themselves.  I turned off autoscanning back in the day because there were too many problems with serial port timeouts and messing with unrelated devices.

We're working on a backend now that's designed to support multiple machines simultaneously, so until then the best bet is to sit tight.  If you really need it, we could probably add some command-line parameters that would set the machine and serial port, and then you could launch an instance of ReplicatorG for each machine with a script.

**Comment by koenkooi** [comment]
My mendel is actually using makerbot mobo and EC with latest firmware, the only difference I have are the stepper controllers, 1/8 microstepping pololu 1201s.

But the multi-machine repG sounds really awesome!

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
