### ISSUE TITLE
Extruder Heatup Fail-Safe

### ISSUE THREAD

**Issue by starno** [makerbot/ReplicatorG#177]
Request for some sort of print abort when heating for extended period of time without a change in temperature feedback.  

For Gen4 electronics, if themocouple is hooked up backwards to the EC, it will give a temp feedback of zero, and you run the risk of overdriving/burning out the hotend.  Breakdown of PTFE tube is also a huge risk.

**Comment by charlespax** [comment]
We can probably put a temperature floor for the thermocouple. If the thermocouple is reversed, the temperature will read as decreasing when the temperature is actually increasing (I think).

**Comment by phooky** [comment]
So, we have multiple scenarios here:
1) The thermocouple is hooked up backwards.
2) The thermocouple is disconnected.

1) is easy to detect; the temperature will be low and the gradient inverted.  2) is a more difficult problem: the temperature can be anything based on whatever static charge is on the pins.  The easiest way to detect it is to check responsiveness heating.

Reporting the problem is a whole other can of worms.

I'll look into this.  It's really a G3Firmware issue, not a repG issue.

**Comment by starno** [comment]
If the firmware treats negative temps as static or zero, and is programed to disable the heater port after running 2min with small change in feedback, could that solve both scenarios?  Build ends with the "build complete 2 min" notification?

**Comment by charlespax** [comment]
According to the documentation,

Bit D2 is normally low and goes high if the thermocou-
ple input is open. In order to allow the operation of the
open thermocouple detector, T- must be grounded.
Make the ground connection as close to the GND pin
as possible.

Spec sheet: http://datasheets.maxim-ic.com/en/ds/MAX6675.pdf

**Comment by phooky** [comment]
Matt Mets is on the case!

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
