### ISSUE TITLE
2D Build Simulation doesn't seem to honor axis being flipped in onboard preferences

### ISSUE THREAD

**Issue by DaveDurant** [makerbot/ReplicatorG#89]
If you do Machine->Onboard Prefs then flip your X and/or Y axis, the 2D Build Simulation during a build doesn't reflect those flips - it looks backwards (or mirrored) from what the machine is actually doing.

**Comment by phooky** [comment]
As it stands ReplicatorG is completely unaware that there's a flipped axis; the reversal happens entirely in firmware.  This is by design; the idea is that you'd flip your axes on the machine to match what ReplicatorG thinks it's doing.  (Originally the goal here was to deal with stepper motors that were wired up the wrong way around.)

**Comment by DaveDurant** [comment]
Maybe the description is just wrong but I still think there's something funky here.. 

If I flip X, the X+ jog button moves the platform to the left, Y+ moves the platform to the front and the resulting object looks just like what skeinview shows but the 2D simulation looks like it's backwards on Y.

RepG 0018, mobo 2.2, extruder 2.3, no HBP.

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/

**Comment by phooky** [comment]
Migrated to Lighthouse: http://replicatorg.lighthouseapp.com/projects/66325/tickets/
